/* Generated by wayland-scanner 1.26.0. Included from p_wayland.c. */

extern struct wl_interface wl_surface_interface;
extern const struct wl_interface wp_alpha_modifier_surface_v1_interface;

static const struct wl_interface *alpha_modifier_v1_types[] = {
	NULL,
	&wp_alpha_modifier_surface_v1_interface,
	&wl_surface_interface,
};

static const struct wl_message wp_alpha_modifier_v1_requests[] = {
	{ "destroy", "", alpha_modifier_v1_types + 0 },
	{ "get_surface", "no", alpha_modifier_v1_types + 1 },
};

WL_PRIVATE const struct wl_interface wp_alpha_modifier_v1_interface = {
	"wp_alpha_modifier_v1", 1,
	2, wp_alpha_modifier_v1_requests,
	0, NULL,
};

static const struct wl_message wp_alpha_modifier_surface_v1_requests[] = {
	{ "destroy", "", alpha_modifier_v1_types + 0 },
	{ "set_multiplier", "u", alpha_modifier_v1_types + 0 },
};

WL_PRIVATE const struct wl_interface wp_alpha_modifier_surface_v1_interface = {
	"wp_alpha_modifier_surface_v1", 1,
	2, wp_alpha_modifier_surface_v1_requests,
	0, NULL,
};

